### ISSUE TITLE
cannot set target translation language as permanent.

### ISSUE THREAD

**Issue by joschan** [fastaddons/WebTranslate#3]
**Describe the bug**  
The settings allows users to choose different target translation language. However, when translate a new word, the target translation language always pick the top of the language list, which is "Afrikaans"

**Steps To Reproduce**  
1. On web page, select the words
2. rigth click and open ... Translate "selected word" 
3. The problem is that the target language always the first/top of the language list which is "Afrikaans". Change to "Japanese"
4. Repeat step 1 and 2
5. Translated to "Arfikaans"

Check settings, it was set to "Japanese"

**Expected behavior**  
The target language should be set to the preferred language until manual intervention.

**Device info:**
 - Windows 10
 - Brave Version 1.19.86 Chromium: 88.0.4324.96 (Official Build) (64-bit)
 - WebTranslate 2.9
![Screenshot 2021-01-22 121120](https://user-images.githubusercontent.com/55565615/105436466-fc2dfc80-5caa-11eb-8769-9a586b62686d.png)

**Additional info**
Add any other info about the problem here.

**Comment by Juraj-Masiar** [comment]
Hello, could you check your settings?
On the left side click the gear icon and see the "Translate to" field at the top. This is the default translation language.

**Comment by joschan** [comment]
Hi, my mistakes, it wasn't the "Japanese" language having the problem, I can confirm "Japanese" stays. However, I was using "Chinese (Simple)" and also tried "Chinese (Traditional)". I will provide screen shots.
Screen shot 1: in Settings, I set to Chinese (Simple)
Screen shot 2: I set to Chinese (Simple)
Screen shot 3: I triggered your translation program, and it reverted back to "Afrikaans"


![Screenshot 2021-01-22 193012](https://user-images.githubusercontent.com/55565615/105473255-a1b39100-5ce8-11eb-8af1-11efe99b2a61.png)
![Screenshot 2021-01-22 193041](https://user-images.githubusercontent.com/55565615/105473274-a7a97200-5ce8-11eb-9a9b-df3f2c17b7a6.png)
![Screenshot 2021-01-22 193109](https://user-images.githubusercontent.com/55565615/105473283-abd58f80-5ce8-11eb-99de-38da2c6d4f86.png)

**Comment by fastaddons** [comment]
Ah, yes, this is actually a different problem.
The "Google Translate" provider is broken in Chrome (due to new security protection) and it works only in Firefox.
So in Chrome the translator will fall-back to the "Microsoft Translator" - but this doesn't support that many languages so if it doesn't find target language it will choose the fist one it finds.

Anyway, what you should do is switch to "Microsoft Translator" in the Settings and then choose target language from the updated list - this will contain only supported languages.

In the next version I will try to fix this somehow to avoid confusion...

**Comment by joschan** [comment]
Yes. Thank you for the explanation. I have changed to Microsoft Translator as advised. Working well so far.
